### ISSUE TITLE
Expand ~

### ISSUE THREAD

**Issue by Aloso** [adam-mcdaniel/dune#4]
With `cd ~` I would like to go to my home directory. I'd also like to be able to type `vim ~/.dune-prelude` to edit the prelude.

To accomplish this, dune should replace `~` at the beginning of a path with the home directory. A string should be considered a path if it

1. Is not in double quotes
2. It equals `~`, or it starts with `~/`

For example, when typing

```sh
$ foo bar ~ ~~ ~baz ~/hello ./~
```

Then the following arguments should be passed to `foo` (assuming the home directory is `/home/aloso`):

```py
[ "bar", "/home/aloso", "~~", "~baz", "/home/aloso/hello", "./~" ]
```

(This is also what bash does.)

**Comment by adam-mcdaniel** [comment]
I don't like the idea of parsing the contents of a `Symbol` type expression and replacing `~` with another value during evaluation; it goes against my design philosophy. I don't want certain variable names to have different significance or be interpreted varying ways before/after quoting.

However, there are a _lot_ of ways you can write abstractions to get the behavior you want already. Take this image, for example:
![image](https://user-images.githubusercontent.com/28228031/135150592-45af5bef-dc92-40c7-9185-fab5d21204da.png)
This makes it so that whenever you call `cd` with no arguments it returns to the home directory. You could easily implement something like this in your `.dune-prelude`.

Additionally, if you want to use `~` to refer to files relative to the home directory, you could do something a bit creative like this:
![image](https://user-images.githubusercontent.com/28228031/135150993-ec15c50f-9d04-4e9c-9ef0-57449b60b778.png)
This defines `~` as a lambda function that creates a path relative to the `HOME` directory.

**Comment by Aloso** [comment]
> This defines `~` as a lambda function that creates a path relative to the `HOME` directory.

I like this idea! Thanks for your help.
