### ISSUE TITLE
Optimize string allocations in parser

### ISSUE THREAD

**Issue by adam-mcdaniel** [adam-mcdaniel/dune#44]
In the parser, as pointed out by @Aloso in #43, the parser spends most of its time allocating strings.

I believe this is probably from making calls to `input.to_string()`, which takes the entire remainder of the input program and allocates it to a string.

I think we may be able to optimize this by using `Display` instead of `ToString`, and then using a format call such as: `format!("{:<width$}", input, width=MAX_INPUT_TO_SAVE)`. This would only grab the first `MAX_INPUT_TO_SAVE` number of characters from the input, as the user is not going to want to read the whole input to see where it failed to parse.

However, this specific fix would only work if `format!` only calls as much as it needs to given the format specifiers.

Another easier (and probably better) fix that would _guarantee_ that `format!` only calls as much as it needs to is to limit it ourselves in the implementation of `Display` for `Tokens`. We might do something like the following:

```rs
const MAX_TOKENS_TO_DISPLAY: usize = 15;

impl fmt::Display for Tokens<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Only display for first 15 tokens
        // from the start of the input.
        for t in self.0.iter().take(MAX_TOKENS_TO_DISPLAY) {
            write!(f, "{} ", t)?;
        }
        Ok(())
    }
}
```

I think this implementation would be a good solution.

**Comment by Aloso** [comment]
P.S. allocations could be further reduced by using _small strings_ (e.g. for `Symbol`). [This cool bear's blog has written about it](https://fasterthanli.me/articles/small-strings-in-rust). It's also possible to use a _string interner_ as [this blog post describes](https://dev.to/cad97/string-interners-in-rust-797).

Another option (which I personally like very much) is to use text ranges instead of `&str`, which allows moving the original string around without having to worry about lifetimes. Text ranges are very flexible: You can safely join adjacent ranges, create them anywhere since they don't carry a lifetime, and find out what text come before or after the range (e.g. to provide context for an error).

I wrote a crate for this when I was writing a parser some time ago: [detached_str](https://docs.rs/detached-str/0.1.0/detached_str/).

Ideally, creating a new `SyntaxError` should be allocation-free. I really like [thiserror](https://docs.rs/thiserror/1.0.29/thiserror/) for this use case.
