### ISSUE TITLE
Cannot redirect output to a file with `>`

### ISSUE THREAD

**Issue by markpbaggett** [adam-mcdaniel/dune#8]
Hello, 

I'd like to redirect output to a file like:

```
curl https://loon.lib.utk.edu/scout-pdfs/MS.2271.pdf > MS_2271.pdf
```

Dune doesn't like this and ultimately I end up with something like this:

```
curl https://loon.lib.utk.edu/scout-pdfs/MS.2271.pdf > MS_2271.pdf
                            > 
syntax error:
 | on input `://loon.lib.utk.edu/scout-pdfs/MS.2271.pdf > MS_2271.pdf`
 | expected Eof
```

**Comment by adam-mcdaniel** [comment]
There are actually TWO issues here:
1. It seems that I forgot to add `:` to the list of allowed characters in a symbol. That's an easy fix.

2. As for the file redirection, I think we need different operators like `>>` and `<<` for it to work. This is because `>` and `<` have higher precedence than application / program execution.

So, I think I'll implement two builtin functions (basically the same as lisp special forms) `redirect-out` and `redirect-in` these will be called as follows:

```bash
redirect-out (curl https://loon.lib.utk.edu/scout-pdfs/MS.2271.pdf) MS_2271.pdf
```

Then, in the parser, I'll have new operators like `>>` and `<<` with lower precedence which will expand to `redirect-out` and `redirect-in` calls respectively.

```bash
"Hello!" >> test.txt
# becomes
redirect-out "Hello!" test.txt
```

**Comment by adam-mcdaniel** [comment]
![image](https://user-images.githubusercontent.com/28228031/135536833-50dcfeac-67cf-4abc-8169-e96677b6d442.png)

Approaching piping and file redirection...

**Comment by adam-mcdaniel** [comment]
![image](https://user-images.githubusercontent.com/28228031/135670748-1a21ceff-85a5-49b8-a201-5a5dc77d04b4.png)

Almost done :)

**Comment by markpbaggett** [comment]
@adam-mcdaniel, fantastic.  Thanks for working on this.  😎
